language: php
php:
- 7.2
- 7.1
- 7.0
- 5.6
- 5.5
- 5.4
- hhvm
install:
- composer install
after_script:
- vendor/bin/test-reporter --coverage-report build/logs/clover.xml
addons:
  apt:
    packages:
    - php5-curl
  code_climate:
