language: php
php:
- 7.2
- 7.1
- 7.0
- 5.6
- 5.5
- 5.4
install:
- composer install
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
